#!/usr/bin/env python3
"""Build a scope.json from targets typed on the command line.

    ./dual-agent/mkscope.py '*.target.com' 203.0.113.0/24 \
        --exclude blog.target.com --rps 5 --header 'X-Bug-Bounty: handle'

Domains, IPs and CIDRs are sorted into the right buckets automatically. The
result is what scope-guard.py enforces, so this is the difference between
"I told the agent the scope" and "the agent cannot leave the scope".

Refuses to overwrite an existing scope.json without --force.
"""

import argparse
import ipaddress
import json
import os
import sys

DEFAULT_EXCLUDED_FINDINGS = [
    "self-XSS",
    "missing security headers without demonstrated impact",
    "rate limiting on non-authentication endpoints",
    "clickjacking on unauthenticated pages",
    "vulnerabilities requiring physical access or a rooted device",
    "reports from automated scanners without a working proof of concept",
]


def bucket(value):
    """Classify a target as an ip entry or a domain entry."""
    try:
        ipaddress.ip_network(value, strict=False)
        return "ips"
    except ValueError:
        return "domains"


def normalize(value):
    value = value.strip().lower().rstrip("/")
    for prefix in ("http://", "https://"):
        if value.startswith(prefix):
            value = value[len(prefix):]
    try:
        # A CIDR's prefix length is not a URL path - keep it intact.
        ipaddress.ip_network(value, strict=False)
        return value
    except ValueError:
        pass
    return value.split("/")[0].split(":")[0]


def split_targets(values):
    out = {"domains": [], "ips": []}
    for raw in values:
        value = normalize(raw)
        if not value:
            continue
        key = bucket(value)
        if value not in out[key]:
            out[key].append(value)
    return out


def main():
    ap = argparse.ArgumentParser(description="Generate a scope.json for a hunt.")
    ap.add_argument("targets", nargs="+",
                    help="in-scope domains, wildcards, IPs or CIDRs")
    ap.add_argument("--exclude", action="append", default=[],
                    help="out-of-scope host (repeatable)")
    ap.add_argument("--rps", type=int, default=5,
                    help="max requests per second (default: 5)")
    ap.add_argument("--header", default="",
                    help="header to send on every request, e.g. 'X-Bug-Bounty: handle'")
    ap.add_argument("--ref", default="",
                    help="URL of the program policy authorizing this testing")
    ap.add_argument("--name", default="", help="engagement name")
    ap.add_argument("--out", default="scope.json", help="output path")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing scope file")
    args = ap.parse_args()

    if os.path.exists(args.out) and not args.force:
        sys.exit(f"error: {args.out} already exists. Pass --force to replace it, "
                 "or edit it directly.")

    in_scope = split_targets(args.targets)
    out_scope = split_targets(args.exclude)

    if not in_scope["domains"] and not in_scope["ips"]:
        sys.exit("error: no usable targets given")

    primary = (in_scope["domains"] or in_scope["ips"])[0].lstrip("*.")

    scope = {
        "engagement": args.name or primary,
        "authorization": {
            "type": "bug-bounty",
            "reference": args.ref,
            "authorized_by": "operator-asserted at scope creation",
            "valid_until": "",
        },
        "in_scope": in_scope,
        "out_of_scope": {
            "domains": out_scope["domains"],
            "ips": out_scope["ips"],
            "findings": DEFAULT_EXCLUDED_FINDINGS,
        },
        "rules": {
            "max_requests_per_second": args.rps,
            "no_dos": True,
            "no_social_engineering": True,
            "no_data_exfiltration": True,
            "pii_handling": "stop at proof of access, never dump records",
            "required_header": args.header,
        },
        "notes": ("Generated by mkscope.py. Agents must refuse any target not "
                  "matching in_scope. Destructive verbs require explicit human "
                  "confirmation."),
    }

    with open(args.out, "w") as fh:
        json.dump(scope, fh, indent=2)
        fh.write("\n")

    print(f"Wrote {args.out}")
    print(f"  in scope:     {', '.join(in_scope['domains'] + in_scope['ips'])}")
    if out_scope["domains"] or out_scope["ips"]:
        print(f"  excluded:     {', '.join(out_scope['domains'] + out_scope['ips'])}")
    print(f"  rate limit:   {args.rps}/s")
    if args.header:
        print(f"  header:       {args.header}")
    if not args.ref:
        print("  note:         no program policy URL recorded (--ref)")


if __name__ == "__main__":
    main()
